version: '3.8'

services:
  attendancesystemapi:
    image: attendancesystemapi
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-api
    restart: unless-stopped
    ports:
      - "5070:8080"
    volumes:
      - attendance_images:/app/wwwroot/images
    networks:
      - attendance_network

volumes:
  attendance_images:
  # postgres_data: # Uncomment if using PostgreSQL

networks:
  attendance_network:
    driver: bridge
