version: '3.8'

services:
  attendancesystemapi:
    image: attendancesystemapi
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-api
    restart: unless-stopped
    ports:
      - "5070:8080"
    volumes:
      # Volume for uploaded images (optional if using S3)
      - attendance_images:/app/wwwroot/images
    networks:
      - attendance_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  attendance_images:
  # postgres_data: # Uncomment if using PostgreSQL

networks:
  attendance_network:
    driver: bridge
